CREATE SMALLFILE TABLESPACE "TBS_IIS" DATAFILE '/oracle/oradata/orcl/TBS_IIS.DBF' SIZE 10M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "TBS_IIS_INDEX" DATAFILE '/oracle/oradata/orcl/TBS_IIS_INDEX.DBF' SIZE 10M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

