CREATE SMALLFILE TABLESPACE "TBS_IISTP" DATAFILE '/oracle/oradata/orcl/TBS_IISTP.DBF' SIZE 10M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "TBS_IISTP_INDEX" DATAFILE '/oracle/oradata/orcl/TBS_IISTP_INDEX.DBF' SIZE 10M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE 32767M LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

